### ISSUE TITLE
cannot open mannual pdf

### ISSUE THREAD

**Issue by wangshuang2024** [xihaoli/MultiSTAAR#1]
@xihaoli Hello, Xihao. The manual pdf is not available to download. Could you share another one? Thank you.

**Comment by xihaoli** [comment]
Hi @wangshuang2024,

Thanks for reaching out. Are you referring to this [MultiSTAAR manual pdf file](https://github.com/xihaoli/MultiSTAAR/blob/main/docs/MultiSTAAR_manual.pdf)? If so, there should be a "Download raw file" button on the upper right corner for you to download.

Let me know if it works.

Best,
Xihao

**Comment by wangshuang2024** [comment]
> Hi @wangshuang2024,
> 
> Thanks for reaching out. Are you referring to this [MultiSTAAR manual pdf file](https://github.com/xihaoli/MultiSTAAR/blob/main/docs/MultiSTAAR_manual.pdf)? If so, there should be a "Download raw file" button on the upper right corner for you to download.
> 
> Let me know if it works.
> 
> Best, Xihao

![image](https://github.com/xihaoli/MultiSTAAR/assets/147407943/8d7f6c35-3c77-4323-92da-918c7070cb5c)
hello, Xihao. the pdf file showed "Invalid PDF"

**Comment by xihaoli** [comment]
Hi @wangshuang2024,

Are you able to download the manual by clicking the down arrow on the upper right corner? If not, you may check [this post](https://github.com/orgs/community/discussions/64419) and see if it works.

Best,
Xihao
